---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rollout-canary-multi-service-hpa
  namespace: argo-cd
spec:
  project: argocd-rollout-example
  source:
    repoURL: https://github.com/unchaptered/ArgoCD-Rollout-Examples
    targetRevision: main
    path: argo-cd-canary-multi-service-hpa
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated: {}