---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-rollout-example
  namespace: argo-cd
spec:
  description: "ArgoCD-Rollout-Examples"
  sourceRepos:
    - https://github.com/unchaptered/ArgoCD-Rollout-Examples
  destinations:
    - name: in-cluster
      namespace: default
      server: https://kubernetes.default.svc
    - name: in-cluster
      namespace: argo-cd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'