---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-rollout-examples
  namespace: default

spec:
  description: "ArgoCD-Rollout-Examples"
  sourceRepos:
    - https://github.com/unchaptered/ArgoCD-Rollout-Examples
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - kube-system