---
apiVersion: argoproj.io/v1alpha1     
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: blue-green-hpa
spec:
  # application
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: blue-green-hpa
  template:
    metadata:
      labels:
        app: blue-green-hpa
    spec:
      containers:
      - name: blue-green-hpa-container
        # image: argoproj/rollouts-demo:blue
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 20m
          limits:
            cpu: 50m
  # strategy
  strategy:
    blueGreen:
      activeService: blue-green-hpa-activate
      previewService: blue-green-hpa-prview
      autoPromotionEnabled: false