---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blue-green-hpa
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: blue-green-hpa
  targetCPUUtilizationPercentage: 80

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60