---
apiVersion: v1
kind: Service
metadata:
  name: argocd-rollout-blue-green-prview
spec:
  selector:
    app: argocd-rollout-blue-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30082
  type: NodePort