---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-hpa-activate
spec:
  selector:
    app: blue-green-hpa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30181
  type: NodePort