---
apiVersion: v1
kind: Service
metadata:
  name: argocd-rollout-canary-prview
spec:
  selector:
    app: argocd-rollout-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30092
  type: NodePort