---
apiVersion: argoproj.io/v1alpha1     
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: argocd-rollout-canary
spec:
  # application
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argocd-rollout-canary
  template:
    metadata:
      labels:
        app: argocd-rollout-canary
    spec:
      containers:
      - name: argocd-rollout-canary-container
        # image: argoproj/rollouts-demo:blue
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  # strategy
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      steps:
      - setWeight: 33
      - pause:
          duration: 15s
      - setWeight: 67
      - pause:
          duration: 30s
      - setWeight: 100
      # Ephemeral Metadata to capture by Prometheus, Wavefront, DataDog
      # https://argo-rollouts.readthedocs.io/en/stable/features/ephemeral-metadata/
      stableMetadata:
        labels:
          role: stable
      canaryMetadata:
        labels:
          role: canary