---
apiVersion: v1
kind: Service
metadata:
  name: canary-hpa-prview
spec:
  selector:
    app: canary-hpa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30092
  type: NodePort