---
apiVersion: argoproj.io/v1alpha1     
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: canary-hpa
spec:
  # application
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: canary-hpa
  template:
    metadata:
      labels:
        app: canary-hpa
    spec:
      containers:
      - name: canary-hpa-container
        # image: argoproj/rollouts-demo:blue
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  # strategy
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      steps:
      - setWeight: 33
      - pause:
          duration: 15s
      - setWeight: 67
      - pause:
          duration: 30s
      - setWeight: 100