---
apiVersion: v1
kind: Service
metadata:
  name: canary-hpa-activate
spec:
  selector:
    app: canary-hpa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30091
  type: NodePort