---
apiVersion: v1
kind: Service
metadata:
  name: argocd-rollout-example-activate
spec:
  selector:
    app: argocd-rollout-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30081
  type: NodePort